"""empty message

Revision ID: 294c8e40d07b
Revises: 3595fd409847
Create Date: 2024-05-12 12:41:12.265145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294c8e40d07b'
down_revision = '3595fd409847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('status', sa.SmallInteger(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'status')
    # ### end Alembic commands ###
