"""empty message

Revision ID: 3595fd409847
Revises: 6ea4c7f2a545
Create Date: 2024-04-21 19:54:26.937149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3595fd409847'
down_revision = '6ea4c7f2a545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_column('image', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('image', 'title')
    # ### end Alembic commands ###
