"""empty message

Revision ID: 916948382ea9
Revises: af10b584c20e
Create Date: 2026-01-18 21:13:33.925520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916948382ea9'
down_revision = 'af10b584c20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_column('entry', 'author_id')
    # ### end Alembic commands ###
